### ISSUE TITLE
How to set the network connection timeout option ?

### ISSUE THREAD

**Issue by itsalongstory** [net-ssh/net-sftp#129]
Hello team, 

How to set the network connection `timeout` option ?

**Comment by tatums** [comment]
+1 

This would be very helpful.  In my case calling `Net::SFTP.start` on a sftp server that never replies will just wait indefinitely.

**Comment by ajsharma** [comment]
You should be able to pass in a `timeout` option when calling start.

`Net::SFTP.start(host, user, timeout: 1)` 

not obvious, but it should map to `Net::SSH.start` which does take a timeout.

**Comment by ka8725** [comment]
> You should be able to pass in a `timeout` option when calling start.
> 
> `Net::SFTP.start(host, user, timeout: 1)`
> 
> not obvious, but it should map to `Net::SSH.start` which does take a timeout.

When username and password should be passed, it's also not obvious, the call with timeout should be like this:

```ruby
Net::SFTP.start(host, user, {timeout: 1}, {username: '...', password: '...'})
```

The first hash comes into the `Net::SSH.start`.
