### ISSUE TITLE
Specifying ssh keys only possible with piggy backing?

### ISSUE THREAD

**Issue by solars** [net-ssh/net-sftp#52]
Hi there,

I wondered how I can connect to an SFTP Server and specify my keys (custom location). I first thought it isn't possible but then discovered that you can piggy-back on a net-ssh connection. net-ssh allows to define a location for the keys so I ended up with:

Net::SSH.start('server', 'seekda', {keys: ['mykeyfile'], passphrase: 'pass'}) do |ssh|
  ssh.sftp.connect do |sftp|
    sftp.dir.foreach(".") do |entry|
      puts entry.longname
    end
  end
end

Is there a way to do this with SFTP directly?
I think it would make sense to add it to the documentation otherwise as many people are looking for it.

Thanks,
Christoph

**Comment by mfazekas** [comment]
You should be able to pass net-ssh options to net-sftp directiy.

```
Net::SFTP.start('host', 'username', password: 'password', keys: ['mykeyfile'], ...) do |sftp|
```
