### ISSUE TITLE
net-sftp hanging indefinitely; PR wanted?

### ISSUE THREAD

**Issue by duncan-bayne** [net-ssh/net-sftp#57]
One of our clients is experiencing a production bug where net-sftp is looping indefinitely.  We believe this is because the server to which they're connecting stops receiving data, but doesn't close the connection.

I'd like to submit a PR with a configurable time-out, but I note that net-sftp is in maintenance mode. @delano, would you in principle be interested in such a PR?

**Comment by mfazekas** [comment]
@duncan-bayne what is the net-ssh version? Have you tried with https://rubygems.org/gems/net-ssh/versions/4.0.0.rc1? 
Is this something that can be reproduced?

**Comment by guillec** [comment]
Upgrading the SSH gem to version 4.1.0 helped my situation. 
I was having a strange problem where a Delayed::Job would hang while uploading a file. 
It would upload a file but never close the connection. 

The strange thing is that this would only happen when triggering Delayed::Job manually. 

Upgrading my ssh gem fixed the problem for my situation.

**Comment by cyclotron3k** [comment]
I think this is a problem I'm facing too, but I'm finding it difficult to reliably replicate.

**Comment by duncan-bayne** [comment]
Happy to close this; haven't worked on it in over three years :)

**Comment by AquisTech** [comment]
@duncan-bayne I am having some issues in uploading to SFTP. Not able to figure out. Could you tell me, in your case, was there any error returned after prolonged hanging?

**Comment by misdoro** [comment]
hanging can be caused by protocol issue, can you try if the patch from https://github.com/net-ssh/net-ssh/pull/672 solves it for you ?

**Comment by duncan-bayne** [comment]
Haven't used in many years (~ 7 now!).  Closing.
