### ISSUE TITLE
After ~300MB the file download fails

### ISSUE THREAD

**Issue by danielmyasnikov** [net-ssh/net-sftp#63]
Could you please navigate me how to debug this issue. Happens in production not on local server

**Comment by mfazekas** [comment]
What is the error you're receiving?

**Comment by bobber205** [comment]
Are people psychic where you live? Give some details man, that's github 101.

**Comment by mfazekas** [comment]
Closing the issue for lack of details. Feel free to add information, i'll reopen then.
