### ISSUE TITLE
Hangs on login with local vsftp

### ISSUE THREAD

**Issue by badosu** [net-ssh/net-sftp#79]
Net-sftp gets stuck right after `SFTP.start` is called.

Running it in verbose mode results in:

```
D, [2018-09-11T09:50:10.862251 #32249] DEBUG -- net.ssh.transport.session[2b0f2a109528]: establishing connection to localhost:21
D, [2018-09-11T09:50:10.862518 #32249] DEBUG -- net.ssh.transport.session[2b0f2a109528]: connection established
I, [2018-09-11T09:50:10.862552 #32249]  INFO -- net.ssh.transport.server_version[2b0f2a108920]: negotiating protocol version
D, [2018-09-11T09:50:10.862565 #32249] DEBUG -- net.ssh.transport.server_version[2b0f2a108920]: local is `SSH-2.0-Ruby/Net::SSH_5.0.2 x86_64-linux'
```

The corresponding log for vsftp, running in localhost:

```
Tue Sep 11 09:50:10 2018 [pid 2] CONNECT: Client "127.0.0.1"
Tue Sep 11 09:50:10 2018 [pid 2] FTP response: Client "127.0.0.1", "220 (vsFTPd 3.0.3)"
Tue Sep 11 09:50:10 2018 [pid 2] FTP command: Client "127.0.0.1", "SSH-2.0-RUBY/NET::SSH_5.0.2 x86_64-linux"
Tue Sep 11 09:50:10 2018 [pid 2] FTP response: Client "127.0.0.1", "530 Please login with USER and PASS."
Tue Sep 11 09:53:13 2018 [pid 2] [badosu] DEBUG: Client "127.0.0.1", "Control connection terminated without SSL shutdown."
Tue Sep 11 09:55:10 2018 [pid 2] FTP response: Client "127.0.0.1", "421 Timeout."
```

<details>
<summary>vsftpd.conf</summary>
<pre>
# Example config file /etc/vsftpd.conf
#
# The default compiled in settings are fairly paranoid. This sample file
# loosens things up a bit, to make the ftp daemon more usable.
# Please see vsftpd.conf.5 for all compiled in defaults.
#
# READ THIS: This example file is NOT an exhaustive list of vsftpd options.
# Please read the vsftpd.conf.5 manual page to get a full idea of vsftpd's
# capabilities.
#
# Allow anonymous FTP? (Beware - allowed by default if you comment this out).
anonymous_enable=NO
#
# Uncomment this to allow local users to log in.
local_enable=YES
#
# Uncomment this to enable any form of FTP write command.
write_enable=YES
#
# Default umask for local users is 077. You may wish to change this to 022,
# if your users expect that (022 is used by most other ftpd's)
#local_umask=022
#
# Uncomment this to allow the anonymous FTP user to upload files. This only
# has an effect if the above global write enable is activated. Also, you will
# obviously need to create a directory writable by the FTP user.
#anon_upload_enable=YES
#
# Uncomment this if you want the anonymous FTP user to be able to create
# new directories.
#anon_mkdir_write_enable=YES
#
# Activate directory messages - messages given to remote users when they
# go into a certain directory.
dirmessage_enable=YES
#
# Activate logging of uploads/downloads.
#
# Make sure PORT transfer connections originate from port 20 (ftp-data).
connect_from_port_20=YES
#
# If you want, you can arrange for uploaded anonymous files to be owned by
# a different user. Note! Using "root" for uploaded files is not
# recommended!
#chown_uploads=YES
#chown_username=whoever
user_sub_token=$USER
local_root=/home/$USER/ftp
#
# You may override where the log file goes if you like. The default is shown
# below.
#xferlog_file=/var/log/vsftpd.log
#
# If you want, you can have your log file in standard ftpd xferlog format.
# Note that the default log file location is /var/log/xferlog in this case.
#xferlog_std_format=YES
#
# You may change the default value for timing out an idle session.
#idle_session_timeout=600
#
# You may change the default value for timing out a data connection.
#data_connection_timeout=120
#
# It is recommended that you define on your system a unique user which the
# ftp server can use as a totally isolated and unprivileged user.
#nopriv_user=ftpsecure
#
# Enable this and the server will recognise asynchronous ABOR requests. Not
# recommended for security (the code is non-trivial). Not enabling it,
# however, may confuse older FTP clients.
#async_abor_enable=YES
#
# By default the server will pretend to allow ASCII mode but in fact ignore
# the request. Turn on the below options to have the server actually do ASCII
# mangling on files when in ASCII mode.
# Beware that on some FTP servers, ASCII support allows a denial of service
# attack (DoS) via the command "SIZE /big/file" in ASCII mode. vsftpd
# predicted this attack and has always been safe, reporting the size of the
# raw file.
# ASCII mangling is a horrible feature of the protocol.
#ascii_upload_enable=YES
#ascii_download_enable=YES
#
# You may fully customise the login banner string:
#ftpd_banner=Welcome to blah FTP service.
#
# You may specify a file of disallowed anonymous e-mail addresses. Apparently
# useful for combatting certain DoS attacks.
#deny_email_enable=YES
# (default follows)
#banned_email_file=/etc/vsftpd.banned_emails
#
# You may specify an explicit list of local users to chroot() to their home
# directory. If chroot_local_user is YES, then this list becomes a list of
# users to NOT chroot().
# (Warning! chroot'ing can be very dangerous. If using chroot, make sure that
# the user does not have write access to the top level directory within the
# chroot)
chroot_local_user=YES
chroot_list_enable=YES
# (default follows)
chroot_list_file=/etc/vsftpd.chroot_list
#
# You may activate the "-R" option to the builtin ls. This is disabled by
# default to avoid remote users being able to cause excessive I/O on large
# sites. However, some broken FTP clients such as "ncftp" and "mirror" assume
# the presence of the "-R" option, so there is a strong case for enabling it.
#ls_recurse_enable=YES
#
# When "listen" directive is enabled, vsftpd runs in standalone mode and
# listens on IPv4 sockets. This directive cannot be used in conjunction
# with the listen_ipv6 directive.
listen=YES
#
# This directive enables listening on IPv6 sockets. To listen on IPv4 and IPv6
# sockets, you must run two copies of vsftpd with two configuration files.
# Make sure, that one of the listen options is commented !!
#listen_ipv6=YES
pasv_enable=YES
pasv_min_port=40000
pasv_max_port=50000
#force_local_logins_ssl=YES
allow_writeable_chroot=YES
ssl_enable=YES
# if you accept anonymous connections, you may want to enable this setting
#allow_anon_ssl=NO
# by default all non anonymous logins and forced to use SSL to send and receive password and data, set to NO to allow non secure connections
# force_local_logins_ssl=NO
# force_local_data_ssl=NO
# TLS v1 protocol connections are preferred and this mode is enabled by default while SSL v2 and v3 are disabled
# the settings below are the default ones and do not need to be changed unless you specifically need SSL
#ssl_tlsv1=YES
#ssl_sslv2=NO
#ssl_sslv3=NO
# provide the path of your certificate and of your private key
# note that both can be contained in the same file or in different files
rsa_cert_file=/etc/ssl/certs/vsftpd.pem
rsa_private_key_file=/etc/ssl/certs/vsftpd.pem
# this setting is set to YES by default and requires all data connections exhibit session reuse which proves they know the secret of the control channel.
# this is more secure but is not supported by many FTP clients, set to NO for better compatibility
require_ssl_reuse=NO
xferlog_std_format=NO
log_ftp_protocol=YES
seccomp_sandbox=NO
xferlog_enable=YES
</pre>
</details>

**Comment by badosu** [comment]
It also does not work with bftpd locally.

**Comment by badosu** [comment]
Misconfiguration, closing.

**Comment by nspriego** [comment]
Hi @badosu Can you shed some light on what the misconfiguration was here?

**Comment by badosu** [comment]
Sorry, I don't have the slightest idea what I did here anymore.

**Comment by nspriego** [comment]
I figured, it was quite some time ago. At this point Im throwing Hail
Marys.. :) Thanks for the response
