### ISSUE TITLE
Release 2.1.3

### ISSUE THREAD

**Issue by Laykou** [net-ssh/net-sftp#85]
Would you please be able to make official release 2.1.3 so that we can pull from Ruby gems instead of master branch?

We are interested in the performance optimization merged in https://github.com/net-ssh/net-sftp/pull/82

**Comment by mfazekas** [comment]
@Laykou have you tried `2.1.3.rc2` did it work for you?

**Comment by mfazekas** [comment]
I don't think we'll release `2.1.3.rc-s` because of potential semver issues. We might have a `3.0.0` soon
