### ISSUE TITLE
Blocking real SFTP connections in test environment

### ISSUE THREAD

**Issue by itmart** [net-ssh/net-sftp#88]
Hi,

We are using Minitest to test our code and we usually stub out the SFTP request so it won't hit the real SFTP server. But in the case that we forgot to do that, is there a way to block real SFTP requests?

Thanks!

**Comment by mfazekas** [comment]
@itmart i guess you can use the :proxy option to make sure you cannot connect to actual servers or  mock `Socket.tcp` as net-ssh uses that to open tcp sockets.

**Comment by itmart** [comment]
@mfazekas Thanks for replying! Is there an example of the `:proxy` option you're referring to? I tried to find it but I couldn't find it the docs. This is the docs I'm looking at: https://www.rubydoc.info/gems/net-sftp/2.0.5/Net/SFTP.

I'll also look into mocking `Socket.tcp`!

**Comment by mfazekas** [comment]
`:proxy` is an `net-ssh` option see 
https://www.rubydoc.info/github/net-ssh/net-ssh/Net/SSH
you can pass something non nil to it like:

`proxy: :disable_net_connections`

that will raise an error whever you try to connect to anywhere

**Comment by itmart** [comment]
I see, I will look into the `:proxy` option and see if I can figure anything out. Thank you for your suggestions!

**Comment by 9mm** [comment]
How do we pass the net-ssh config into net-sftp?

**Comment by TheUrbina20** [comment]
@itmart did you figure this out?

**Comment by tylerhunt** [comment]
If you pass a `:proxy` option like `Net::SFTP.start host, username, proxy: :no_connect`, it will raise a `Socket::ResolutionError` error.
